__author__ = 'vivan'

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''


def even_fibonacci(n):
    a, b, total = 0, 1, 0
    while b < n:
        # Check if fibonacci number is even
        if b % 2 == 0:
            total += b
        a, b = b, a+b
    return total

print even_fibonacci(4000000)